version: "3"
services:
  snmpsim:
    build: .
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ../../integration_specs/snmpsim/simulated_data/:/simulated_data
    ports:
     - 1161:1161/udp
