sudo: required

services:
- docker

language: python

python:
- '3.7'

before_install:
- sudo apt-get -y update || true

install:
- dev/setup_venv.sh

before_script:
- echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
- dev/start_infsnmp3_dependencies.sh

script:
- dev/all_tests.sh
- docker logout

notifications:
  email:
    - bifer@alea-soluciones.com
