sudo: required

services:
- docker

language: python

python:
- '3.7'

before_install:
- sudo apt-get -y update || true

install:
- dev/setup_venv.sh

script:
- dev/integration_tests.sh

notifications:
  email:
    - bifer@alea-soluciones.com
