services:
  - docker

os: linux

dist: focal

language: python

python:
  - '3.7'

install:
  - dev/setup_venv.sh

before_script:
  - echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
  - dev/start_infsnmp3_dependencies.sh

script:
  - all_tests

after_script:
  - dev/stop_infsnmp3_dependencies.sh
  - docker logout

notifications:
  email:
    - bifer@alea-soluciones.com
