services:
  - docker

os: linux

dist: focal

language: python

python:
  - '3.7'
  - '3.8'
  - '3.9'

install:
  - dev/setup_venv.sh
  - python -m pip install --no-cache-dir --upgrade pip wheel setuptools
  - python -m pip install --no-cache-dir -r requirements-versioned.txt
  - python -m pip install --no-cache-dir -r requirements-git.txt
  - python -m pip install --no-cache-dir -r requirements-dev.txt
  - python -m pip install -e .

before_script:
  - echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USER --password-stdin
  - dev/start_infsnmp3_dependencies.sh

script:
  - all_tests

after_script:
  - dev/stop_infsnmp3_dependencies.sh
  - docker logout

notifications:
  email:
    - bifer@alea-soluciones.com
